sudo: required
dist: trusty
language: python
python: '2.7'
env:
- ANSIBLE_VERSION=latest
- ANSIBLE_VERSION=2.4
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
- ansible-galaxy install geerlingguy.apache
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-playbook -i tests/inventory tests/test.yml -vvvv --skip-tags update,copy_host_ssh_id
notifications:
  pushover:
    api_key:
      secure: bAIE87yWhrq+MH12FMg60lDXGJYXhMx7mJMXTIsOLvkGgXr3pN0nuJz/Y4C9zrCf+/gtstfcA00nxRn2wfcYo8UbxEoNeV1VSsHWkiFAcSRD3oEcW5a6xJAmzYW7CFjaoOxzOWWG5dQrqf8Hk2kUnqYXkRnZ/kEPF8VDsguX4rrhT803XlAzQIDIJtMomLIDeMXw0YSXotGJHhU7hN866I7TCtmE3IvjIezsCgfYN3qsNIjv34HjqsNy1seAA1SCMclFnXWQCML6QVT+O6EWrgcYiQOQWi6dMP3zTn0eO3v4c2J0X8h87hBJ7zsCPKmrzby14Dd2fChhdI9gAHWB176wP727IQtPsqNWcpo82AJZdGeAOiaE2vYAWLee5v5i/gB/q9z4hrtHFzdPaWjgu48tJFN1hZ5IWJb17/X9AmP1EaQ/K0CrAo6T+eIFWOneCciy+R+kSM13bZGbGDkhRYjJg7Ev/bxvkawH6DKJ2TmKN1jXCQWO/Oe8A8QshCkI7Pw1SM8SKYPgc917ouHZ7zT6wopv8mDV/ZcqWuZGDjXmOIm2rcGuAyjoPo4ZY4NcLuZbjN4l/Qr51aqJBkzLc2FQKQehKQDhn3eI2m4KNACT2rx6EHqx92sn0WA+5pvwXIrB75wO01QyCiQ2e9i1mHCXs8rXk/E9xmI375GH/cI=
    users:
      secure: dDvo2HpzeOZ6g3GFhooaN43pCWjcPR/n2t3qG58KfE1SVM9CzTLR6gB3gQ2+ZxfOQsFNMJssIEYmnbTPizKQpwLVe8DRNoZ+6cAMuHIoxuMBv1htyPkl0TvwmHFWR7gc7XojnsrOphlW9sW8I1C893TjFbPaPM0XaUr0YuNjRhJoWVnI2iiuhPZNuY84VKmRjHmwvlWFqnczSQ01UAQc9DYbPtkPvQycUlE1vuPML9Dk3X2ZLqdTP6VhAlNVvUzo59geTKdAS38xGDfpGJJ+mxRyGqfCaQhfzNYuogDqcoBl68ZiTM0dRjSWOWwyS/u14ljxbkppmWajH+KSuX8na+PkjwLQNlHawWFf8LicQov1KqUkANDCtp6t9Y6yFyp0AlswFzZj02obE6FBWYRjnxTwZtmfYomC8N1g9Jhw6C6CT+K2v0nE9tzffds7cH169civ/5KFi0WspPq5KgEsDXTEwURAEArIiIIuSOlDEKYXANTctPy64RlkmlVxF7tMFbQaIKO+OJBPnwj+HWrdbfeAfAoWMiuTarUAa8WuReCWksAtHfIZqnZ+9bD58ddk1H9tmAJBdMj3QrIbEWbarbtrGRSSK/0UyLbJn4NQvBVkmKRSMlZ3I7ofUttTqCVXt/81GcO2lo9J40y+iay+CuCCoTBTx9XghvHC1xH7L44=
