---
- name: Creates /tmp/ directory
  file: path=/tmp/ state=directory

- name: Download mod_jk source 1.2.44 locally with check (sha256)
  get_url:
    url: http://mirrors.sonic.net/apache/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.44-src.tar.gz
    dest: /tmp/tomcat-connectors-1.2.44-src.tar.gz
    checksum: sha512:3fcb291a5cdc4fded4a7b5570572ac6dcc0016b880c12199c0669905f526f43a6f87608a49defed274a509021bb9763997c51ca4ad7f659b650ffc362c510f61

- name: Creates /tmp/modjk directory
  file: path=/tmp/modjk/ state=directory

- name: Extract tomcat-connectors-1.2.44-src.tar.gz
  unarchive:
    src: /tmp/tomcat-connectors-1.2.44-src.tar.gz
    dest: /tmp/modjk/
    list_files: yes

- name: Install apache2 development apache2-dev
  apt:
    name: apache2-dev
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install apache2 development httpd-devel
  yum:
    name: httpd-devel
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# - name: Check apache has DSO support
